//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIViewerMap.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POIViewerMap.Resources.Strings.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AppUsageCloseButtonText {
            get {
                return ResourceManager.GetString("AppUsageCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author of this app cannot guarantee the accuracy of any POI that appears on the map. Discretion is required at all times whilst using the app. The data is extracted from Open Street Maps and relies on the many OSM contributors. Particular attention should be taken in regards to Drinking Water Points as there is no guarantee that any shown on the map are fit for drinking and the user must seek local knowledge..
        /// </summary>
        internal static string AppUsageDisclaimerLabelText {
            get {
                return ResourceManager.GetString("AppUsageDisclaimerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string AppUsageDisclaimerTitleLabelText {
            get {
                return ResourceManager.GetString("AppUsageDisclaimerTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI Viewer Map.
        /// </summary>
        internal static string AppUsagePopupTitleMsg {
            get {
                return ResourceManager.GetString("AppUsagePopupTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Map On My Position.
        /// </summary>
        internal static string CenterMapLabelText {
            get {
                return ResourceManager.GetString("CenterMapLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        internal static string ChooseCountryText {
            get {
                return ResourceManager.GetString("ChooseCountryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string ChooseText {
            get {
                return ResourceManager.GetString("ChooseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string CountryLabelText {
            get {
                return ResourceManager.GetString("CountryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this message again.
        /// </summary>
        internal static string DoNotShowAgainLabelText {
            get {
                return ResourceManager.GetString("DoNotShowAgainLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route import failed!!.
        /// </summary>
        internal static string ImportRouteFailedMessage {
            get {
                return ResourceManager.GetString("ImportRouteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not used.
        /// </summary>
        internal static string OptionsFileListImportLabelText {
            get {
                return ResourceManager.GetString("OptionsFileListImportLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import GPX Route.
        /// </summary>
        internal static string OptionsImportRouteButtonText {
            get {
                return ResourceManager.GetString("OptionsImportRouteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        internal static string OptionsPOIPickerATMText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerATMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakery.
        /// </summary>
        internal static string OptionsPOIPickerBakeryText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerBakeryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle Repair Station.
        /// </summary>
        internal static string OptionsPOIPickerBicycleRepairStationText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerBicycleRepairStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle Shop.
        /// </summary>
        internal static string OptionsPOIPickerBicycleShopText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerBicycleShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        internal static string OptionsPOIPickerCafeText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerCafeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campsite.
        /// </summary>
        internal static string OptionsPOIPickerCampsiteText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerCampsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking Water.
        /// </summary>
        internal static string OptionsPOIPickerDrinkingWaterText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerDrinkingWaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string OptionsPOIPickerLaundryText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerLaundryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picnic Table.
        /// </summary>
        internal static string OptionsPOIPickerPicnicTableText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerPicnicTableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket.
        /// </summary>
        internal static string OptionsPOIPickerSupermarketText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerSupermarketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilet.
        /// </summary>
        internal static string OptionsPOIPickerToiletText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerToiletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Station.
        /// </summary>
        internal static string OptionsPOIPickerTrainStationText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerTrainStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vending Machine.
        /// </summary>
        internal static string OptionsPOIPickerVendingMachineText {
            get {
                return ResourceManager.GetString("OptionsPOIPickerVendingMachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OptionsRouteDeleteButtonText {
            get {
                return ResourceManager.GetString("OptionsRouteDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        internal static string PinLabelDistanceText {
            get {
                return ResourceManager.GetString("PinLabelDistanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access:.
        /// </summary>
        internal static string PinLabelSubtitleAccessText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle Tubes.
        /// </summary>
        internal static string PinLabelSubtitleBicycleTubeText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleBicycleTubeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread.
        /// </summary>
        internal static string PinLabelSubtitleBreadText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleBreadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string PinLabelSubtitleCustomersText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleCustomersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet:.
        /// </summary>
        internal static string PinLabelSubtitleDietText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleDietText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string PinLabelSubtitleElectronicsText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleElectronicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open:.
        /// </summary>
        internal static string PinLabelSubtitleOpen {
            get {
                return ResourceManager.GetString("PinLabelSubtitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissive.
        /// </summary>
        internal static string PinLabelSubtitlePermissiveText {
            get {
                return ResourceManager.GetString("PinLabelSubtitlePermissiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string PinLabelSubtitlePrivateText {
            get {
                return ResourceManager.GetString("PinLabelSubtitlePrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump.
        /// </summary>
        internal static string PinLabelSubtitlePump {
            get {
                return ResourceManager.GetString("PinLabelSubtitlePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle Refill Here.
        /// </summary>
        internal static string PinLabelSubtitleRefill {
            get {
                return ResourceManager.GetString("PinLabelSubtitleRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services:.
        /// </summary>
        internal static string PinLabelSubtitleServicesText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleServicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        internal static string PinLabelSubtitleStand {
            get {
                return ResourceManager.GetString("PinLabelSubtitleStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        internal static string PinLabelSubtitleTelephoneText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleTelephoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string PinLabelSubtitleTools {
            get {
                return ResourceManager.GetString("PinLabelSubtitleTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string PinLabelSubtitleTypeText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PinLabelSubtitleUnknown {
            get {
                return ResourceManager.GetString("PinLabelSubtitleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan Only.
        /// </summary>
        internal static string PinLabelSubtitleVeganOnlyText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleVeganOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan Option.
        /// </summary>
        internal static string PinLabelSubtitleVeganOptionText {
            get {
                return ResourceManager.GetString("PinLabelSubtitleVeganOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string PinLabelSubtitleWebsite {
            get {
                return ResourceManager.GetString("PinLabelSubtitleWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIs.
        /// </summary>
        internal static string POIBrowseButtonText {
            get {
                return ResourceManager.GetString("POIBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI Filename:.
        /// </summary>
        internal static string POIFilepathLabelText {
            get {
                return ResourceManager.GetString("POIFilepathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import POIs for Country:.
        /// </summary>
        internal static string POIImportCountryLabelText {
            get {
                return ResourceManager.GetString("POIImportCountryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string POIImportServerText {
            get {
                return ResourceManager.GetString("POIImportServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance:.
        /// </summary>
        internal static string POIMaxDistanceLabel {
            get {
                return ResourceManager.GetString("POIMaxDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string POIPickerTitleText {
            get {
                return ResourceManager.GetString("POIPickerTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIs Found:.
        /// </summary>
        internal static string POIsFoundLabelText {
            get {
                return ResourceManager.GetString("POIsFoundLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading POIs - please wait....
        /// </summary>
        internal static string POIsLoadingLabelText {
            get {
                return ResourceManager.GetString("POIsLoadingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI:.
        /// </summary>
        internal static string POIViewerMapPOIsLabelText {
            get {
                return ResourceManager.GetString("POIViewerMapPOIsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI Viewer Map.
        /// </summary>
        internal static string POIViewerTitle {
            get {
                return ResourceManager.GetString("POIViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Options On Startup.
        /// </summary>
        internal static string RestoreOptionsOnStartupLabelText {
            get {
                return ResourceManager.GetString("RestoreOptionsOnStartupLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Filename:.
        /// </summary>
        internal static string RestoreUIStateRouteFilename {
            get {
                return ResourceManager.GetString("RestoreUIStateRouteFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route:.
        /// </summary>
        internal static string RouteFilepathLabelText {
            get {
                return ResourceManager.GetString("RouteFilepathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing GPX route....
        /// </summary>
        internal static string RouteLoadingLabelText {
            get {
                return ResourceManager.GetString("RouteLoadingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Radius:.
        /// </summary>
        internal static string SearchRadiusLabelText {
            get {
                return ResourceManager.GetString("SearchRadiusLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Access Failed.
        /// </summary>
        internal static string ServerAccessFailedMsg {
            get {
                return ResourceManager.GetString("ServerAccessFailedMsg", resourceCulture);
            }
        }
    }
}
